export const homeContent = {
  heroBadge: '{{HERO_BADGE}}',
  heroHeadline: '{{HERO_HEADLINE}}',
  heroSubheadline: '{{HERO_SUBHEADLINE}}',
  heroPrimaryCta: '{{CTA_BUTTON_PRIMARY}}',
  heroSecondaryCta: '{{CTA_BUTTON_SECONDARY}}',
  trustItems: [
    '{{TRUST_ITEM_1}}',
    '{{TRUST_ITEM_2}}',
    '{{TRUST_ITEM_3}}',
    '{{TRUST_ITEM_4}}',
  ],
  metrics: [
    { value: '{{METRIC_VALUE_1}}', label: '{{METRIC_LABEL_1}}', sub: '{{METRIC_SUB_1}}' },
    { value: '{{METRIC_VALUE_2}}', label: '{{METRIC_LABEL_2}}', sub: '{{METRIC_SUB_2}}' },
    { value: '{{METRIC_VALUE_3}}', label: '{{METRIC_LABEL_3}}', sub: '{{METRIC_SUB_3}}' },
    { value: '{{METRIC_VALUE_4}}', label: '{{METRIC_LABEL_4}}', sub: '{{METRIC_SUB_4}}' },
  ],
  servicesSectionTitle: '{{SERVICES_SECTION_TITLE}}',
  servicesSectionBody: '{{SERVICES_SECTION_BODY}}',
  howItWorksTitle: '{{HOW_IT_WORKS_TITLE}}',
  howItWorksSteps: [
    '{{HOW_IT_WORKS_STEP_1}}',
    '{{HOW_IT_WORKS_STEP_2}}',
    '{{HOW_IT_WORKS_STEP_3}}',
    '{{HOW_IT_WORKS_STEP_4}}',
  ],
  whyUsTitle: '{{WHY_US_TITLE}}',
  whyUsBody: '{{WHY_US_BODY}}',
  whyUsPoints: ['{{WHY_US_POINT_1}}', '{{WHY_US_POINT_2}}', '{{WHY_US_POINT_3}}'],
  testimonialsTitle: '{{TESTIMONIALS_TITLE}}',
  testimonials: [
    { quote: '{{TESTIMONIAL_QUOTE_1}}', client: '{{CLIENT_NAME_1}}', role: '{{CLIENT_ROLE_1}}' },
    { quote: '{{TESTIMONIAL_QUOTE_2}}', client: '{{CLIENT_NAME_2}}', role: '{{CLIENT_ROLE_2}}' },
  ],
  coverageTitle: '{{COVERAGE_TITLE}}',
  coverageBody: '{{COVERAGE_BODY}}',
  ctaTitle: '{{CTA_HEADLINE}}',
  ctaSubtitle: '{{CTA_SUBHEADLINE}}',
  ctaButton: '{{CTA_BUTTON_TEXT}}',
};
