export const pricingContent = {
  heroTitle: '{{PRICING_HERO_TITLE}}',
  heroSubtitle: '{{PRICING_HERO_SUBTITLE}}',
  heroCtaQuote: '{{PRICING_HERO_CTA_QUOTE}}',
  heroCtaPdf: '{{PRICING_HERO_CTA_PDF}}',
  pdfHref: '{{PRICING_PDF_URL}}',
  tiers: [
    {
      id: 'essential',
      name: '{{PRICING_TIER_ESSENTIAL_NAME}}',
      tagline: '{{PRICING_TIER_ESSENTIAL_TAGLINE}}',
      price: '{{PRICING_ESSENTIAL_PRICE}}',
      unit: '{{PRICING_ESSENTIAL_UNIT}}',
      features: [
        '{{PRICING_FEATURE_ESSENTIAL_1}}',
        '{{PRICING_FEATURE_ESSENTIAL_2}}',
        '{{PRICING_FEATURE_ESSENTIAL_3}}',
        '{{PRICING_FEATURE_ESSENTIAL_4}}',
      ],
      cta: '{{PRICING_TIER_ESSENTIAL_CTA}}',
      popular: false,
    },
    {
      id: 'professional',
      name: '{{PRICING_TIER_PROFESSIONAL_NAME}}',
      tagline: '{{PRICING_TIER_PROFESSIONAL_TAGLINE}}',
      price: '{{PRICING_PROFESSIONAL_PRICE}}',
      unit: '{{PRICING_PROFESSIONAL_UNIT}}',
      features: [
        '{{PRICING_FEATURE_PROFESSIONAL_1}}',
        '{{PRICING_FEATURE_PROFESSIONAL_2}}',
        '{{PRICING_FEATURE_PROFESSIONAL_3}}',
        '{{PRICING_FEATURE_PROFESSIONAL_4}}',
      ],
      cta: '{{PRICING_TIER_PROFESSIONAL_CTA}}',
      popular: true,
      popularLabel: '{{PRICING_MOST_POPULAR_LABEL}}',
    },
    {
      id: 'enterprise',
      name: '{{PRICING_TIER_ENTERPRISE_NAME}}',
      tagline: '{{PRICING_TIER_ENTERPRISE_TAGLINE}}',
      price: '{{PRICING_ENTERPRISE_PRICE}}',
      unit: '{{PRICING_ENTERPRISE_UNIT}}',
      features: [
        '{{PRICING_FEATURE_ENTERPRISE_1}}',
        '{{PRICING_FEATURE_ENTERPRISE_2}}',
        '{{PRICING_FEATURE_ENTERPRISE_3}}',
        '{{PRICING_FEATURE_ENTERPRISE_4}}',
      ],
      cta: '{{PRICING_TIER_ENTERPRISE_CTA}}',
      popular: false,
    },
  ],
  perServiceTableTitle: '{{PRICING_PER_SERVICE_TABLE_TITLE}}',
  perServiceRows: [
    {
      service: '{{PRICING_ROW_SERVICE_1}}',
      coverage: '{{PRICING_ROW_COVERAGE_1}}',
      price: '{{PRICING_ROW_PRICE_1}}',
      sla: '{{PRICING_ROW_SLA_1}}',
    },
    {
      service: '{{PRICING_ROW_SERVICE_2}}',
      coverage: '{{PRICING_ROW_COVERAGE_2}}',
      price: '{{PRICING_ROW_PRICE_2}}',
      sla: '{{PRICING_ROW_SLA_2}}',
    },
    {
      service: '{{PRICING_ROW_SERVICE_3}}',
      coverage: '{{PRICING_ROW_COVERAGE_3}}',
      price: '{{PRICING_ROW_PRICE_3}}',
      sla: '{{PRICING_ROW_SLA_3}}',
    },
  ],
  comparisonTitle: '{{PRICING_COMPARISON_TITLE}}',
  comparisonFeatures: [
    { name: '{{PRICING_COMPARE_FEATURE_1}}', essential: true, professional: true, enterprise: true },
    { name: '{{PRICING_COMPARE_FEATURE_2}}', essential: true, professional: true, enterprise: true },
    { name: '{{PRICING_COMPARE_FEATURE_3}}', essential: false, professional: true, enterprise: true },
    { name: '{{PRICING_COMPARE_FEATURE_4}}', essential: false, professional: true, enterprise: true },
    { name: '{{PRICING_COMPARE_FEATURE_5}}', essential: false, professional: false, enterprise: true },
  ],
  addonsTitle: '{{PRICING_ADDONS_TITLE}}',
  addons: [
    { title: '{{PRICING_ADDON_1_TITLE}}', description: '{{PRICING_ADDON_1_DESC}}', price: '{{PRICING_ADDON_1_PRICE}}' },
    { title: '{{PRICING_ADDON_2_TITLE}}', description: '{{PRICING_ADDON_2_DESC}}', price: '{{PRICING_ADDON_2_PRICE}}' },
    { title: '{{PRICING_ADDON_3_TITLE}}', description: '{{PRICING_ADDON_3_DESC}}', price: '{{PRICING_ADDON_3_PRICE}}' },
    { title: '{{PRICING_ADDON_4_TITLE}}', description: '{{PRICING_ADDON_4_DESC}}', price: '{{PRICING_ADDON_4_PRICE}}' },
  ],
  faq: [
    { question: '{{FAQ_QUESTION_PRICING_1}}', answer: '{{FAQ_ANSWER_PRICING_1}}' },
    { question: '{{FAQ_QUESTION_PRICING_2}}', answer: '{{FAQ_ANSWER_PRICING_2}}' },
    { question: '{{FAQ_QUESTION_PRICING_3}}', answer: '{{FAQ_ANSWER_PRICING_3}}' },
  ],
  closingCtaTitle: '{{PRICING_CLOSING_CTA_TITLE}}',
  closingCtaButton: '{{PRICING_CLOSING_CTA_BUTTON}}',
  tableHeaders: {
    service: '{{PRICING_TABLE_HEADER_SERVICE}}',
    coverage: '{{PRICING_TABLE_HEADER_COVERAGE}}',
    price: '{{PRICING_TABLE_HEADER_PRICE}}',
    sla: '{{PRICING_TABLE_HEADER_SLA}}',
    cta: '{{PRICING_TABLE_HEADER_CTA}}',
    feature: '{{PRICING_TABLE_HEADER_FEATURE}}',
    essential: '{{PRICING_TIER_ESSENTIAL_NAME}}',
    professional: '{{PRICING_TIER_PROFESSIONAL_NAME}}',
    enterprise: '{{PRICING_TIER_ENTERPRISE_NAME}}',
  },
};
