export const siteContent = {
  brandName: 'Mint AMC',
  siteUrl: 'https://www.mintamc.com',
  parentCompany: {
    name: 'CONZEX GLOBAL PRIVATE LIMITED',
    url: 'https://www.conzex.com',
    cin: 'U72900DL2021PTC384501',
  },
  divisions: [
    {
      name: 'Mint AMC',
      url: 'https://www.mintamc.com',
      description: 'PAN-India IT AMC, field engineering, and NOC services.',
    },
    {
      name: 'xHosting',
      url: 'https://www.conzex.com',
      description: 'Web hosting, domain registration, and cloud infrastructure.',
    },
    {
      name: 'xData Center',
      url: 'https://dcops.conzex.com',
      description: 'Data centre colocation, dcops, and managed infrastructure.',
    },
    {
      name: 'Defendx',
      url: 'https://www.defendx.io',
      description: 'Next-gen cybersecurity, threat detection, and SOC services.',
    },
    {
      name: 'UiDRAC SaaS',
      url: 'https://uidrac.cloud.conzex.com',
      description: 'Universal iDRAC & out-of-band server management SaaS platform.',
    },
  ],
  contact: {
    businessEmail: 'info@mintamc.com',
    supportEmail: 'support@mintamc.com',
    email: 'info@mintamc.com',
    phone: '(+91) 800 7060 308',
    nocHotline: '(+91) 800 7060 308',
    headquarters: 'Noida, National Capital Region, India',
    workingHours: '24/7 Support Available · Real-time Monitoring & Client Dashboard',
  },
  nav: {
    home: { label: 'Home', href: '/' },
    solutions: { label: 'Solutions', href: '/solutions' },
    pricing: { label: 'Pricing', href: '/pricing' },
    why: { label: 'Why Mint AMC', href: '/why-mint-amc' },
    about: { label: 'About', href: '/about' },
    resources: { label: 'Resources', href: '/resources' },
    contact: { label: 'Contact', href: '/contact' },
    services: { label: 'Services', href: '/services' },
  },
  megaMenuFooterCta: 'Not sure which AMC scope fits your environment?',
  megaMenuFooterLink: 'Talk to an engineer',
  headerCta: 'Request quote',
  footerTagline:
    'Enterprise IT annual maintenance contracts, field engineering, and optional 24/7 NOC for multi-location organisations across India.',
  footerServicesHeading: 'Services',
  footerAllServicesLink: 'View all AMC services',
  footerDivisionsHeading: 'Conzex group',
  footerLegalHeading: 'Legal',
  footerPrivacyLink: 'Privacy Policy',
  footerTermsLink: 'Terms of Service',
  footerSlaLink: 'SLA overview',
};
