export const siteContent = {
  brandName: '{{BRAND_NAME}}',
  siteUrl: 'https://www.mintamc.com',
  parentCompany: {
    name: '{{PARENT_COMPANY_NAME}}',
    url: 'https://www.conzex.com',
    cin: '{{PARENT_CIN}}',
    dpiit: '{{DPIIT_RECOGNITION_ID}}',
  },
  divisions: [
    { name: '{{DIVISION_CONZEX_HOSTING_NAME}}', url: 'https://www.conzex.com', description: '{{DIVISION_CONZEX_HOSTING_DESC}}' },
    { name: '{{DIVISION_MINT_AMC_NAME}}', url: 'https://www.mintamc.com', description: '{{DIVISION_MINT_AMC_DESC}}' },
    { name: '{{DIVISION_CONZEX_DC_NAME}}', url: '{{DIVISION_CONZEX_DC_URL}}', description: '{{DIVISION_CONZEX_DC_DESC}}' },
    { name: '{{DIVISION_CONZEX_SECURITY_NAME}}', url: '{{DIVISION_CONZEX_SECURITY_URL}}', description: '{{DIVISION_CONZEX_SECURITY_DESC}}' },
  ],
  contact: {
    email: '{{CONTACT_EMAIL}}',
    phone: '{{CONTACT_PHONE}}',
    nocHotline: '{{NOC_HOTLINE}}',
    escalationEmail: '{{ESCALATION_EMAIL}}',
    headquarters: '{{HEADQUARTERS_ADDRESS}}',
    workingHours: '{{WORKING_HOURS}}',
  },
  nav: {
    home: { label: '{{NAV_HOME}}', href: '/' },
    solutions: { label: '{{NAV_SOLUTIONS}}', href: '/solutions' },
    pricing: { label: '{{NAV_PRICING}}', href: '/pricing' },
    why: { label: '{{NAV_WHY_MINT_AMC}}', href: '/why-mint-amc' },
    about: { label: '{{NAV_ABOUT}}', href: '/about' },
    resources: { label: '{{NAV_RESOURCES}}', href: '/resources' },
    contact: { label: '{{NAV_CONTACT}}', href: '/contact' },
    services: { label: '{{NAV_SERVICES}}', href: '/services' },
  },
  megaMenuFooterCta: '{{MEGA_MENU_FOOTER_CTA}}',
  megaMenuFooterLink: '{{MEGA_MENU_FOOTER_LINK}}',
  headerCta: '{{HEADER_CTA_BUTTON}}',
  footerTagline: '{{FOOTER_TAGLINE}}',
  footerServicesHeading: '{{FOOTER_SERVICES_HEADING}}',
  footerAllServicesLink: '{{FOOTER_ALL_SERVICES_LINK}}',
  footerDivisionsHeading: '{{FOOTER_DIVISIONS_HEADING}}',
  footerLegalHeading: '{{FOOTER_LEGAL_HEADING}}',
  footerPrivacyLink: '{{FOOTER_PRIVACY_LINK}}',
  footerTermsLink: '{{FOOTER_TERMS_LINK}}',
  footerSlaLink: '{{FOOTER_SLA_LINK}}',
  footerDivisionLine: '{{FOOTER_DIVISION_LINE}}',
};
