export const siteContent = {
  brandName: 'Mint AMC',
  siteUrl: 'https://www.mintamc.com',
  parentCompany: {
    name: 'CONZEX GLOBAL PRIVATE LIMITED',
    url: 'https://www.conzex.com',
    cin: 'U72900DL2021PTC384501',
    dpiit: 'Recognition held via Conzex Global (DPIIT startup recognition)',
  },
  divisions: [
    {
      name: 'Conzex Hosting',
      url: 'https://www.conzex.com',
      description: 'Hosting, domains, VPS, and managed cloud infrastructure.',
    },
    {
      name: 'Mint AMC',
      url: 'https://www.mintamc.com',
      description: 'PAN-India IT AMC, field engineering, and NOC services.',
    },
    {
      name: 'Conzex Data Centre',
      url: 'https://www.conzex.com',
      description: 'Colocation, dedicated servers, and disaster recovery.',
    },
    {
      name: 'Conzex Cyber Security',
      url: 'https://www.conzex.com',
      description: 'Security products, SOC, and managed cyber services.',
    },
  ],
  contact: {
    email: 'support@mintamc.com',
    phone: '+91 11 4920 8800',
    nocHotline: '+91 1800 210 9900',
    escalationEmail: 'escalations@mintamc.com',
    headquarters: 'Noida, National Capital Region, India',
    workingHours: '24/7 NOC for contracted customers · Business office Mon–Sat 9:00–18:00 IST',
  },
  nav: {
    home: { label: 'Home', href: '/' },
    solutions: { label: 'Solutions', href: '/solutions' },
    pricing: { label: 'Pricing', href: '/pricing' },
    why: { label: 'Why Mint AMC', href: '/why-mint-amc' },
    about: { label: 'About', href: '/about' },
    resources: { label: 'Resources', href: '/resources' },
    contact: { label: 'Contact', href: '/contact' },
    services: { label: 'Services', href: '/services' },
  },
  megaMenuFooterCta: 'Not sure which AMC scope fits your environment?',
  megaMenuFooterLink: 'Talk to an engineer',
  headerCta: 'Request quote',
  footerTagline:
    'Enterprise IT annual maintenance contracts, field engineering, and optional 24/7 NOC for multi-location organisations across India.',
  footerServicesHeading: 'Services',
  footerAllServicesLink: 'View all AMC services',
  footerDivisionsHeading: 'Conzex group',
  footerLegalHeading: 'Legal',
  footerPrivacyLink: 'Privacy Policy',
  footerTermsLink: 'Terms of Service',
  footerSlaLink: 'SLA overview',
};
